# Generated by Django 4.1.3 on 2022-11-08 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='neighborhood_association',
            new_name='association',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
    ]
